config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"
  resources :articles do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[index show]
  get 'my_bookings', to: 'pages#my_bookings'
  get 'my_articles', to: 'pages#my_articles'
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_picture

  has_many :bookings, dependent: :destroy
  has_many :articles, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
    if params[:query].present?
      @articles = @articles.where("name ILIKE ?", "%#{params[:query]}%")
    end
  end

  def new
    @article = Article.new
  end

  def show
    # set_article
    @markers = [
      {
        lng: @article.longitude,
        lat: @article.latitude
      }
    ]
    @booking = Booking.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      puts "Article enregistré !" # Debug output
      redirect_to articles_path, notice: "Publié avec succès !", status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # set_article
  end

  def update
    # set_article
    if @article.update(article_params)
      redirect_to articles_path, notice: "L'article a été mis à jour avec succès."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # set_article

    if @article.destroy # Supprime l'article de la base de données
      redirect_to articles_path, notice: "L'article a été supprimé avec succès."
    else
      redirect_to article_path(@article), alert: "Nous n'avons pas pu supprimer l'article"
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:name, :description, :price, :photo, :address)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
    @article = @booking.article
    # @booking.user = current_user
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.article = Article.find(params[:article_id])
    if @booking.save
      redirect_to booking_path(@booking.id), notice: "Reservé avec succès !"
      #redirect_to articles_path, notice: "Reservé avec succès !"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def my_bookings
    @my_bookings = Booking.where(user: current_user)
  end

  def my_articles
    @my_articles = Article.where(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<h1 class='card-title text-center'>Nouvel article</h1>
<%= simple_form_for @article do |f| %>
  <%= f.input :name,
                required: true,
                label: "Nom",
                hint: " 15 caractères maximum",
                input_html: { maxlength: 15, size: 40} %>
  <%= f.input :description %>
  <%= f.input :price, label: "Prix" %>
  <%= f.input :address, label: "Adresse" %>
  <%= f.input :photo, as: :file %>
  <div class="card-body d-flex flex-column align-items-center gap-3">
    <%= f.submit "Publier", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/_form_booking.html.erb
<%= simple_form_for [@article, @booking], data: { turbo: false} do |f| %>
<%#= f.input :article_id,
            as: :hidden,
            input_html: {value: @article.id}%>
<%#= f.input :user_id,
            as: :hidden,
            input_html: {value: current_user.id}%>
  <%= f.input :start_date, label: "Date de début", as: :string, input_html: { data: { controller: "datepicker" } }  %>
  <%= f.input :end_date, label: "Date de fin", as: :string, input_html: { data: { controller: "datepicker" } } %>
  <%= f.submit "Reservez ! 🤓", class: "btn btn-primary" %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editer un article</h1>
<%= simple_form_for @article do |f| %>
  <%= f.input :name,
                required: true,
                label: "Nom",
                hint: " 15 caractères maximum",
                input_html: { maxlength: 15, size: 40} %>
  <%= f.input :description %>
  <%= f.input :price, label: "Prix" %>
  <%= f.input :address, label: "Adresse" %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Mettre à jour", class: "btn btn-primary" %>
<% end %>

app/views/articles/index.html.erb
<%= render 'layouts/banner'%>

<div class="container py-3">
  <div class="row">
    <% @articles.each do |article| %>
      <div class="col-lg-4 col-md-6 pb-4">
        <div class="card border rounded position-relative">
          <div class="card-body d-flex flex-column align-items-center gap-3">
            <div class="card-haut">
                <h4 class="card-title text-center"><%= article.name.capitalize %></h4>
              <% if article.photo.present? %>
                <div class="card-bg-image" style="background-image: url('<%= cl_image_path article.photo.key %>'); height: 150px; width: 200px; "></div>
              <% else %>
                <div class="card-bg-image" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('<%= image_path "logo.png" %>'); height: 150px; width: 200px;"></div>
              <% end %>
            </div>
            <div class="card-text">
              <p class="card-text"><%= truncate(article.description.capitalize, length: 70, separator: ' ', omission: '...') %></p>
              <p class="card-text">Prix : <strong><%= article.price %></strong>€</p>
              <p class="card-text">Utilisateur : <%= article.user.first_name %></p>
            </div>
          <%= link_to 'Détail article', article_path(article), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <%= render 'form'%>
</div>

app/views/articles/show.html.erb
<div class="container py-3">
  <div class="row">
    <div class="col-lg-4 col-md-6">
      <div class="card card-show border rounded position-relative">
        <div class="card-body d-flex flex-column gap-3">
          <h4 class="card-title text-center"><%= @article.name.capitalize %></h4>
              <% if @article.photo.present? %>
                <div class="card-bg-image mx-auto" style="background-image: url('<%= cl_image_path @article.photo.key %>'); height: 150px; width: 200px; "></div>
              <% else %>
                <div class="card-bg-image mx-auto" style="background-image: url('<%= image_path "logo.png" %>'); height: 150px; width: 200px;"></div>
              <% end %>
          <p> <strong> Description :</strong> <%=@article.description%></p>
          <p><strong> Prix :</strong> <%=@article.price%> €</p>
          <p><strong> Utilisateur :</strong> <%=@article.user.first_name%></p>
            <% if @article.user == current_user %>
              <div class="text-center">
                  <%= link_to 'Modifier', edit_article_path, class: 'btn btn-primary btn-show col-md-6' %>
                  <%= link_to "Supprimer", article_path(@article), class: 'btn btn-danger btn-show col-md-6',  data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cet article ?" } %>
              </div>
          <% else %>
            <div class="text-center">
              <button class="btn btn-show btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                Reservation
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
        <div class= "col-md-8">
          <div style="width: 100%; height: 550px;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
        </div>
      </div>
  </div>
</div>

<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Vos dates de reservation</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <%= render "form_booking" %>
  </div>
</div>

app/views/bookings/index.html.erb
<h1>index bookings</h1>

app/views/bookings/new.html.erb
<h1>New bookings</h1>

app/views/bookings/show.html.erb
<div class = "container container-booking ">
      <figure class="text-center">
        <blockquote class="blockquote">
          <h1>Votre article est réservé ! 🤪</h1>
        </blockquote>
        <p small> Hey <cite title="Source Title"><%= @booking.user.first_name %></cite> ton article t'attend pour faire la fête !</p>
      </figure>
  <div class = "row">
    <div class = "col-md-6 d-flex flex-column align-items-center">
      <div class="card card-body mb-3" style="max-width: 540px;">
        <div class="row g-0 ">
          <div class="col-md-4">
            <% if @article.photo.present? %>
                <div class="card-bg-image" style="background-image: url('<%= cl_image_path @article.photo.key %>'); height: 100%; width: 100%; "></div>
              <% else %>
                <div class="card-bg-image" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('<%= image_path "logo.png" %>'); height: 100%; width: 100%;"></div>
            <% end %>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= @article.name.capitalize %></h5>
              <p class="card-text"><%=@article.description%></p>
              <p class="card-text"><strong> Prix :</strong> <%=@article.price%> €</p>
              <p class="card-text"><small class="text-muted"><%=@article.user.first_name%></small></p>
              <% if @booking %>
                <h6><strong> Dates de réservation : </strong></h6>
                <div class="row">
                  <p class="card-text col-md-6">Début :<br> <strong><%= @booking.start_date %></strong></p>
                  <p class="card-text col-md-6"> Fin:<br> <strong><%= @booking.end_date %></strong></p>
                </div>
                <p class="card-text">Adresse :<br> <strong><%= @article.address %></strong></p>
              <% else %>
                <p class="card-text">Pas de réservation en cours.</p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class = col-md-6 >
      <img class ="rounded-image" src = "https://media.istockphoto.com/id/1279483477/photo/we-are-going-to-party-as-if-theres-no-tomorrow.jpg?s=612x612&w=0&k=20&c=wPmd1hxQEDxhG2P-OwDW3EJ0WoyuW-lEBsPa8O09bwU="/>
    </div>
  </div>
</div>

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.18h39.fr/wp-content/uploads/2015/12/conseils-nouvel-an-home.jpg);">
  <div class="container">
    <h1> Vos meilleures soirées, à la maison !</h1>
    <p>Louez le matériel parfait de particulier à particulier et créez des soirées inoubliables à la maison !
        Des moments mémorables à portée de main.</p>
        <div class="row justify-content-center">
        <div class="col-sm-8 my-3">
          <%= form_with url: articles_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Ecrivez un mot"
          %>
          <%= submit_tag "Chercher", name: "", class: "btn btn-primary btn-search" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer fixed-bottom">
    <p> Plus de stress pour vos soirées déjantées </p>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
 <p> Vos meilleures soirées avec ViveLaFete ! 🤪</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViveLaFete</title>
    <link rel = "icon" href = "https://res.cloudinary.com/dpjincxmo/image/upload/v1692952884/logo_f9fgnh.png" type = "image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.js'></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body class='body'>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer'%>

  </body>
</html>

app/views/pages/my_articles.html.erb
<div class="container container-booking">
  <figure class="text-center">
    <blockquote class="blockquote">
      <h1>Liste de vos articles ! 🤪</h1>
    </blockquote>
    <p small>
      Hey <cite title="Source Title"><%= current_user.first_name %></cite>, tes articles t'attendent pour faire la fête !
    </p>
  </figure>
  <div class="image-container">
    <img class="rounded-image" style="text-align: center;" src="https://usagif.com/wp-content/uploads/upgifsok/party-10.gif" alt="Image d'arrière-plan"/>
  </div>
  <div class="row">
    <% @my_articles.each do |article| %>
      <div class="col-md-6 d-flex flex-column align-items-center">
        <div class="card position-relative card-booking-articles mb-3 card-radius" style="max-width: 540px;">
          <div class="card-bg-image-my-articles mx-auto mt-2" style="background-image: <%= article.photo.present? ? 'url(' + cl_image_path(article.photo.key) + ')' : 'linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(' + image_path('logo.png') + ')' %>"></div>
          <div class="card-body">
            <h5 class="card-title text-center"><%= article.name.capitalize %></h5>
            <p class="card-text"> <strong>Description :</strong><%= article.description %></p>
            <h6 class="card-text text-center"><strong>Prix :</strong> <%= article.price %> €</h6>
            <div class="text-center">
                  <%= link_to 'Modifier', edit_article_path(article), class: 'btn btn-primary btn-show col-md-6' %>
                  <%= link_to "Supprimer", article_path(article), class: 'btn btn-danger btn-show col-md-6',  data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cet article ?" } %>
              </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/my_bookings.html.erb
<div class="container container-booking">
  <figure class="text-center">
    <blockquote class="blockquote">
      <h1>Liste de vos réservations ! 🤪</h1>
    </blockquote>
    <p small>
      Hey <cite title="Source Title"><%= current_user.first_name %></cite>, tes articles t'attendent pour faire la fête !
    </p>
  </figure>
  <div class="image-container">
    <img class="rounded-image" style="text-align: center;" src="https://usagif.com/wp-content/uploads/upgifsok/party-32.gif" alt="Image d'arrière-plan"/>
  </div>
  <div class="row">
    <% @my_bookings.each do |booking| %>
      <div class="col-md-6 d-flex flex-column align-items-center">
        <div class="card position-relative card-booking mb-3 card-radius" style="max-width: 540px;">
          <div class="card-bg-image-booking mx-auto mt-2" style="background-image: <%= booking.article.photo.present? ? 'url(' + cl_image_path(booking.article.photo.key) + ')' : 'linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(' + image_path('logo.png') + ')' %>"></div>
          <div class="card-body">
            <h5 class="card-title text-center"><%= booking.article.name.capitalize %></h5>
            <p class="card-text"><%= truncate(booking.article.description, length: 150, separator: ' ', omission: '...') %></p>
            <h6 class="card-text"><strong>Prix :</strong> <%= booking.article.price %> €</h6>
            <h6><strong> Dates de réservation : </strong></h6>
            <p class="card-text col-md-6">Début :<br> <strong><%= booking.start_date %></strong></p>
            <p class="card-text col-md-6"> Fin:<br> <strong><%= booking.end_date %></strong></p>
          </div>
            <p class="card-text"><small class="text-muted"><%= booking.article.user.first_name %></small></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-5" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-5" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="fixed-top navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand" do %>
       <%= image_tag "logo.png", style: "border-radius: 50%;" %>
      <% end %>

      <h5 class="title ml-3">Vive La Fête ! 🎉 </h5>
    </div>x

    <div class="collapse navbar-collapse dropdown" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Trouver un article", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Publier un article", new_article_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown-toggle profile-picture">
            <% if current_user.profile_picture.present? %>
              <%= image_tag current_user.profile_picture, data: { bs_toggle:"dropdown"},  aria_expanded: "false" %>
            <% else %>
              <%= image_tag "party.png", data: { bs_toggle:"dropdown"},  aria_expanded: "false"  %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown" >
              <p >
                Hey <cite title="Source Title"><%= current_user.first_name %></cite> prêt à faire la fête ?
              </p>
              <%= link_to "Mes réservations", my_bookings_path, class: "dropdown-item" %>
              <%= link_to "Mes articles", my_articles_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>